# Generated by Django 3.2.4 on 2021-06-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210527_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.CharField(default='', max_length=50)),
                ('check1', models.CharField(default='', max_length=5)),
                ('check2', models.CharField(default='', max_length=5)),
            ],
        ),
    ]
