# Generated by Django 3.2.4 on 2021-06-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210614_2258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contct',
            new_name='contact',
        ),
    ]
